backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paintings"
    label: "Paintings"
    folder: "paintings"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Available", name: "available", widget: "boolean" }
      - { label: "Category", name: "category", widget: "select", options: ["red", "blue"] }
