name: Generate paintings index

on:
  push:
    paths:
      - 'paintings/*.json'
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate index.json
        run: |
          mkdir -p paintings
          echo "[" > paintings/index.json
          first=true
          for file in paintings/*.json; do
            if [ "$file" != "paintings/index.json" ]; then
              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> paintings/index.json
              fi
              cat "$file" >> paintings/index.json
            fi
          done
          echo "]" >> paintings/index.json

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add paintings/index.json
          git commit -m "🧩 Update paintings/index.json" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
