name: Generate Painting Index

on:
  push:
    paths:
      - 'paintings/*.json'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate index.json
        run: |
          echo "[" > paintings/index.json
          find paintings -type f -name "*.json" ! -name "index.json" \
            | sed 's|paintings/||' \
            | sed 's|^|  "|;s|$|"|' \
            | paste -sd, - >> paintings/index.json
          echo "]" >> paintings/index.json

      - name: Commit index.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add paintings/index.json
          git commit -m "🧩 Update paintings/index.json" || echo "No changes"
          git push
